// Generated by CoffeeScript 1.6.3
(function() {
  var devStory;

  devStory = new Story({
    description: 'As a developer...',
    scenarios: new Backbone.Collection([
      new Scenario({
        title: 'Test 1'
      })
    ])
  });

  $(document).ready(function() {
    var regionEl, storyView;
    storyView = new StoryView({
      model: devStory
    });
    regionEl = $('.project .container')[0];
    window.app = {
      stepDefinitions: new StepDefinitions(),
      region: new Marionette.Region({
        el: regionEl
      })
    };
    return app.region.show(storyView);
  });

}).call(this);
