// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.StoryView = (function(_super) {
    __extends(StoryView, _super);

    function StoryView() {
      this.handleClickAddScenario = __bind(this.handleClickAddScenario, this);
      this.handleClick = __bind(this.handleClick, this);
      _ref = StoryView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    StoryView.prototype.className = 'story';

    StoryView.prototype.template = _.template("<div class=\"card\">\n  <textarea class=\"description\" placeholder=\"As a User...\"><%- description %></textarea>\n</div>\n<ul class=\"scenarios\">\n</ul>\n<button class=\"add-scenario\">Add Scenario</button>");

    StoryView.prototype.events = {
      'click': 'handleClick',
      'click .add-scenario': 'handleClickAddScenario',
      'keyup .card > textarea': 'onShow'
    };

    StoryView.prototype.itemView = ScenarioView;

    StoryView.prototype.initialize = function() {
      return this.collection = this.model.get('scenarios');
    };

    StoryView.prototype.itemViewContainer = ".scenarios";

    StoryView.prototype.onShow = function() {
      this.$('.description').focus();
      this.textarea = this.$el.find('> .card textarea').get(0);
      this.textarea.style.height = "" + this.textarea.scrollHeight + "px";
      return console.log('collection', this.model.get('collection'));
    };

    StoryView.prototype.removeScenario = function(scenario) {
      return this.collection.remove(scenario);
    };

    StoryView.prototype.handleClick = function() {
      return this.$el.toggleClass('selected');
    };

    StoryView.prototype.handleClickAddScenario = function(ev) {
      var scenario;
      ev.preventDefault();
      scenario = new Scenario({
        title: '',
        steps: new Backbone.Collection()
      });
      return this.collection.add(scenario);
    };

    return StoryView;

  })(Marionette.CompositeView);

}).call(this);
